// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: enum_example.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Example.Enumerations {

  /// <summary>Holder for reflection information generated from enum_example.proto</summary>
  public static partial class EnumExampleReflection {

    #region Descriptor
    /// <summary>File descriptor for enum_example.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumExampleReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJlbnVtX2V4YW1wbGUucHJvdG8SFGV4YW1wbGUuZW51bWVyYXRpb25zIlYK",
            "C0VudW1NZXNzYWdlEgoKAmlkGAEgASgFEjsKD2RheV9vZl90aGVfd2VlaxgC",
            "IAEoDjIiLmV4YW1wbGUuZW51bWVyYXRpb25zLkRheU9mVGhlV2Vlayp3CgxE",
            "YXlPZlRoZVdlZWsSCwoHVU5LTk9XThAAEgoKBk1PTkRBWRABEgsKB1RVRVNE",
            "QVkQAhINCglXRURORVNEQVkQAxIMCghUSFVSU0RBWRAEEgoKBkZSSURBWRAF",
            "EgwKCFNBVFVSREFZEAYSCgoGU1VOREFZEAdiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Example.Enumerations.DayOfTheWeek), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Example.Enumerations.EnumMessage), global::Example.Enumerations.EnumMessage.Parser, new[]{ "Id", "DayOfTheWeek" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum DayOfTheWeek {
    [pbr::OriginalName("UNKNOWN")] Unknown = 0,
    [pbr::OriginalName("MONDAY")] Monday = 1,
    [pbr::OriginalName("TUESDAY")] Tuesday = 2,
    [pbr::OriginalName("WEDNESDAY")] Wednesday = 3,
    [pbr::OriginalName("THURSDAY")] Thursday = 4,
    [pbr::OriginalName("FRIDAY")] Friday = 5,
    [pbr::OriginalName("SATURDAY")] Saturday = 6,
    [pbr::OriginalName("SUNDAY")] Sunday = 7,
  }

  #endregion

  #region Messages
  public sealed partial class EnumMessage : pb::IMessage<EnumMessage> {
    private static readonly pb::MessageParser<EnumMessage> _parser = new pb::MessageParser<EnumMessage>(() => new EnumMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EnumMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Example.Enumerations.EnumExampleReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnumMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnumMessage(EnumMessage other) : this() {
      id_ = other.id_;
      dayOfTheWeek_ = other.dayOfTheWeek_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EnumMessage Clone() {
      return new EnumMessage(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "day_of_the_week" field.</summary>
    public const int DayOfTheWeekFieldNumber = 2;
    private global::Example.Enumerations.DayOfTheWeek dayOfTheWeek_ = global::Example.Enumerations.DayOfTheWeek.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Example.Enumerations.DayOfTheWeek DayOfTheWeek {
      get { return dayOfTheWeek_; }
      set {
        dayOfTheWeek_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EnumMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EnumMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (DayOfTheWeek != other.DayOfTheWeek) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (DayOfTheWeek != global::Example.Enumerations.DayOfTheWeek.Unknown) hash ^= DayOfTheWeek.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (DayOfTheWeek != global::Example.Enumerations.DayOfTheWeek.Unknown) {
        output.WriteRawTag(16);
        output.WriteEnum((int) DayOfTheWeek);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (DayOfTheWeek != global::Example.Enumerations.DayOfTheWeek.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DayOfTheWeek);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EnumMessage other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.DayOfTheWeek != global::Example.Enumerations.DayOfTheWeek.Unknown) {
        DayOfTheWeek = other.DayOfTheWeek;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 16: {
            DayOfTheWeek = (global::Example.Enumerations.DayOfTheWeek) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
